kind: ConfigMap
apiVersion: v1
metadata:
  name: wallet-clientsave-config-test
  namespace: default
  uid: eb7fc4ae-1142-4c59-8ea5-f673598247ef
  resourceVersion: '17566720'
  creationTimestamp: '2021-10-15T08:56:51Z'
  managedFields:
    - manager: dashboard
      operation: Update
      apiVersion: v1
      time: '2021-03-18T08:13:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:appsettings.json': {}
data:
  appsettings.json: |
    {
      "Serilog": {
        "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
        "MinimumLevel": {
          "Default": "Information",
          "Override": {
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information",
            "System": "Warning"
          }
        },
        "WriteTo": [
          {
            "Name": "Console",
            "Args": {
              "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] {SourceContext}{NewLine}\t{Message}{NewLine}{Exception}"
            }
          }
        ],
        "Enrich": [
          "FromLogContext"
        ]
      },

      "AllowedHosts": "*",

      "DbConnection": "User ID=wallet;Password=TWfBnz9VEcMIsQJ8IOGx;Host=192.168.49.1;Port=5432;Database=walletdb_api_test_new;Pooling=true;Connection Lifetime=0;",

      "ServiceKey": "client_save",
      "WalletCardStorageServiceKey": "wallet_api",
      "OriginUrl": "https://clientsave.wallet.shelter.ru:10000",

      "RabbitMqConfig": {
                    "Host": "192.168.49.1",
                    "VHost": "wallet-test",
                    "User": "appuser",
                    "Password": "LeJ7bg43LX3akgrOs9rA"
      },
      "ExternalSevices": [
        {
          "Name": "Google Pay",
          "Key": "google_pay",
          "OriginUrl_": "https://googlepay.wallet.shelter.ru:10000",
          "Desc": "Служба GooglePay Wallet",
          "SaveImage": "google.svg",
          "DisabledSaveImage": "google_disabled.svg"
        },
        {
          "Name": "Apple Pass",
          "Key": "apple_pass",
          "OriginUrl_": "https://applepass.wallet.shelter.ru:10000",
          "Desc": "Служба Apple Pass Wallet",
          "SaveImage": "apple.svg",
          "DisabledSaveImage": "apple_disabled.svg"
        }
      ]
    }
