kind: Pod
apiVersion: v1
metadata:
  name: wallet-api-59dd67d979-cnssl
  generateName: wallet-api-59dd67d979-
  namespace: default
  uid: ddcb5223-36e1-4089-86e3-7851f71ff262
  resourceVersion: '18712346'
  creationTimestamp: '2021-10-22T12:31:25Z'
  labels:
    k8s-app: wallet-api
    pod-template-hash: 59dd67d979
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: wallet-api-59dd67d979
      uid: f4713008-d08e-407b-8f1b-bcceffba98ba
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2021-10-22T12:31:25Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:k8s-app': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"f4713008-d08e-407b-8f1b-bcceffba98ba"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:containers':
            'k:{"name":"wallet-api"}':
              .: {}
              'f:image': {}
              'f:imagePullPolicy': {}
              'f:name': {}
              'f:resources': {}
              'f:securityContext':
                .: {}
                'f:privileged': {}
              'f:terminationMessagePath': {}
              'f:terminationMessagePolicy': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/app/appsettings.json"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:subPath': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
          'f:volumes':
            .: {}
            'k:{"name":"config-volume"}':
              .: {}
              'f:configMap':
                .: {}
                'f:defaultMode': {}
                'f:name': {}
              'f:name': {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2022-01-13T16:18:12Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"172.17.0.11"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
spec:
  volumes:
    - name: config-volume
      configMap:
        name: wallet-api-config
        defaultMode: 420
    - name: default-token-xmh4g
      secret:
        secretName: default-token-xmh4g
        defaultMode: 420
  containers:
    - name: wallet-api
      image: 'wallet.shelter.ru:15000/wallet-api'
      resources: {}
      volumeMounts:
        - name: config-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
        - name: default-token-xmh4g
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
      securityContext:
        privileged: false
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: minikube
  securityContext: {}
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-10-22T12:31:25Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-01-13T16:18:01Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-01-13T16:18:01Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-10-22T12:31:25Z'
  hostIP: 192.168.49.2
  podIP: 172.17.0.11
  podIPs:
    - ip: 172.17.0.11
  startTime: '2021-10-22T12:31:25Z'
  containerStatuses:
    - name: wallet-api
      state:
        running:
          startedAt: '2022-01-13T16:18:00Z'
      lastState:
        terminated:
          exitCode: 255
          reason: Error
          startedAt: '2021-12-22T10:46:52Z'
          finishedAt: '2022-01-13T16:15:31Z'
          containerID: >-
            docker://2b35ff351bc8b402e3173e9f67cc0ec5a49a7b0dd90cd9b7d3e3d561ef7b4626
      ready: true
      restartCount: 4
      image: 'wallet.shelter.ru:15000/wallet-api:latest'
      imageID: >-
        docker-pullable://wallet.shelter.ru:15000/wallet-api@sha256:902d6ab4da7addc01655ae69c0b3a35c00b03708e761f42638f92c5152cbbf46
      containerID: >-
        docker://c8c12ef2c2f5061b5f0f20adcb875ec01b9f8e79680955504ea2187d2b1dd73f
      started: true
  qosClass: BestEffort
